export const FALLBACK_VIDEOS = [
  {
    _id: "demo_bbb_1",
    videotitle: "Sample YouTube Video - Big Buck Bunny",
    filename: "BigBuckBunny.mp4",
    filetype: "video/mp4",
    filepath: "https://www.w3schools.com/html/mov_bbb.mp4",
    filesize: "15MB",
    videochanel: "Blender Open Studio",
    Like: 1420,
    views: 35200,
    uploader: "demo_user_1",
  },
  {
    _id: "demo_sintel_2",
    videotitle: "Sintel - Animated Short Film",
    filename: "Sintel.mp4",
    filetype: "video/mp4",
    filepath: "https://media.w3.org/2010/05/sintel/trailer_hd.mp4",
    filesize: "22MB",
    videochanel: "Open Cinema Studio",
    Like: 2310,
    views: 49800,
    uploader: "animator_guy",
  },
  {
    _id: "demo_flower_3",
    videotitle: "Flower Showcase - Nature & Colors",
    filename: "Flower.mp4",
    filetype: "video/mp4",
    filepath: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    filesize: "10MB",
    videochanel: "Nature & Tech Channel",
    Like: 670,
    views: 12300,
    uploader: "tech_reviewer",
  },
];
